select	TRUNC(LAST_DAY(a11.SUBMIT_DT))  LAST_DAY_OF_MONTH,
	max(a19.MTH_NM_SHORT || '-' || TRIM(a19.YEAR_OF_CAL))  CAL_MONTH_DESC,
	a11.ORDER_TYP_DES  ORDER_TYP_DES,
	a17.SEGMENT_DES  SEGMENT_DES,
	a11.ORDER_STATUS_CD  ORDER_STATUS_CD,
	a11.PAYMENT_TYPE_CD  PAYMENT_TYPE_CD,
	NVL(a15.ENTERTAINMENT, 'Unknown')  ENTERTAINMENT,
	NVL(a15.RED_UNLIMITED_GRP, 'Unknown')  RED_UNLIMITED_GRP,
	NVL(a15.RED, 'Unknown')  RED,
	CASE WHEN a11.MSISDN LIKE '447%' AND a11.PRODUCT_CLASS =  'Fixed Broadband Service' THEN 'HBB-Dongle' WHEN a11.MSISDN LIKE '447%' THEN 'MOB' WHEN a11.PRODUCT_CLASS =  'Fixed Broadband Service' THEN 'HBB'  WHEN a11.PRODUCT_CLASS LIKE 'Accessories' THEN 'ACCESSORIES' ELSE 'UNKNOWN' END  CustCol_4,
	a17.ORDER_TYP  ORDER_TYP,
	NVL(a15.PRICE_PLAN_GROUP_NM, 'Unknown')  PRICE_PLAN_GROUP_NM,
	a11.SUBMIT_DT  CALENDAR_DT,
	a11.ORDER_SUBTYP  ORDER_SUBTYP,
	TRIM(CAST((a19.MTH_DAY_NO+(TD_DAY_OF_WEEK( a19.FIRST_DAY_OF_MONTH -1 ) )-2)/7 AS INTEGER)+1) || '.' || TRIM(a19.CAL_WEEK_DAY_NO) || ' ' || a19.DAY_NM_SHORT  CustCol,
	NVL(a12.BRAND_DESC || ' ' ||a12.CMRCL_ID_DESC, 'Not classified at this leve')  CustCol_20,
	Case when a16.PARENT_ORDER_ID IS NOT NULL THEN 'RETURN' ELSE 'SALE' END  Order_Status_Type,
	a14.DES  DES,
	CASE 
WHEN a14.BEARER_DES IN ('5G', '4G', '3G')  THEN a14.BEARER_DES
ELSE 'UNKNOWN TARIFF' END  BEARER_DES,
	a14.PRODUCT_DES_2  PRODUCT_DES_2,
	CASE 
WHEN a12.SKU_CD IS NOT NULL AND a12.BEARER LIKE ('%5G%') THEN  '5G DEVICE'
WHEN a12.SKU_CD IS NOT NULL AND a12.BEARER LIKE ('%4G%') THEN  '4G DEVICE'
WHEN a12.SKU_CD IS NOT NULL AND a12.BEARER LIKE ('%3G%') THEN  '3G DEVICE'
WHEN a12.SKU_CD IS NOT NULL AND a12.BEARER NOT LIKE ANY ('%5G%','%4G%','%3G%') THEN  'UNKNOWN DEVICE' END  CustCol_22,
	CASE WHEN a11.DEVICE_DESC LIKE ANY ('%APPLE%','%iPAD%') THEN  'APPLE'
WHEN a11.DEVICE_DESC LIKE ANY ('%SAMSUNG%','%GALAXY%') THEN  'SAMSUNG'
WHEN a11.DEVICE_DESC LIKE  '%HUAWEI%' THEN  'HUAWEI'
WHEN a11.DEVICE_DESC LIKE ANY('%PIXEL%','%GOOGLE%') THEN  'GOOGLE'
WHEN a11.DEVICE_DESC LIKE  '%SONY%' THEN  'SONY'
WHEN a11.DEVICE_DESC LIKE  '%NOKIA%' THEN  'NOKIA'
WHEN a11.DEVICE_DESC LIKE ANY ('%MOTOROLA%','%MOTO%') THEN  'MOTOROLA'
WHEN a11.DEVICE_DESC LIKE  '%OPPO%' THEN  'OPPO'
WHEN a11.DEVICE_DESC LIKE  '%XIAOMI%' THEN  'XIAOMI'
WHEN a11.DEVICE_DESC LIKE  '%ALCATEL%' THEN  'ALCATEL'
ELSE 'OTHER' END  MANUFACTURER,
	a11.DEVICE_DESC  DEVICE_DESC,
	a11.PROMO_SOC_CD  PROMO_SOC_CD,
	a11.ORDER_TYP_DES  ORDER_TYP_DES0,
	a12.SLOT  SLOT,
	CASE WHEN a11.TRADE_DISC_AMT_INC_VAT > 0 THEN 'TRADE IN OFFER' ELSE 'STANDARD OFFER' END  CustCol_43,
	CASE WHEN a11.ORDER_TYP_DES IN ('New Connection') THEN 'ACQUISITION' ELSE 'RETENTION' END  CustCol_44,
	NVL(a13.LOAN_AIRTIME_PLAN_FLAG, 'Unknown')  CustCol_46,
	NVL((CASE WHEN lower(a13.CONTRACT_TYP) like '%sim only%' THEN a13.PRODUCT_DES_3 ELSE a13.AIRTIME_TIER END), 'Unknown')  DATA_PLAN_GROUP,
	NVL(a13.REPORTED_PRODUCT, 'Unknown')  REPORTED_PRODUCT,
	a14.PRICE_PLAN_BANDING_INC_VAT  PRICE_PLAN_BANDING_INC_VAT,
	a11.CONTRACT_TENURE  CONTRACT_TENURE,
	a14.SERVICE_PRODUCT_SET_NM  SERVICE_PRODUCT_SET_NM,
	a14.PRODUCT_DES  PRODUCT_DES,
	a14.PRODUCT_DES_2  PRODUCT_DES_20,
	a14.DATA_ALLOWANCE_GROUPING  DATA_ALLOWANCE_GROUPING,
	CASE WHEN NVL(a15.ENTERTAINMENT, 'Unknown') ='Entertainment'  THEN 'Entertainment' ELSE 'Non Entertainment' END  ENTERTAINMENT0,
	Case When NVL(a15.RED_UNLIMITED_GRP, 'Unknown') IN ('Red','Non Red','Unknown') Then 'Non Unlimited' else a15.RED_UNLIMITED_GRP end  RED_UNLIMITED_GRP0,
	a11.TRADEIN_FLAG  TRADEIN_FLAG,
	CASE  
WHEN a11.RECUR_DISC_DESC LIKE '%Trade%' THEN 'Trade-In'
WHEN a11.RECUR_DISC_DESC LIKE '%Promo%' THEN 'Promotional' 
WHEN a11.RECUR_DISC_DESC LIKE '%£%' AND a11.RECUR_DISC_DESC LIKE '%Off%' THEN 'Promotional' 
WHEN a11.RECUR_DISC_DESC LIKE '%£%' AND a11.RECUR_DISC_DESC LIKE '%Plan%' THEN 'Promotional'  
WHEN a11.RECUR_DISC_DESC LIKE '%GBP%' THEN 'Promotional' 
WHEN a11.RECUR_DISC_DESC LIKE '%Vodafone Together%' then 'Vodafone Together'
WHEN a11.RECUR_DISC_DESC LIKE '%House%' THEN 'Household'  
WHEN a11.RECUR_DISC_DESC LIKE '%Additional%' THEN 'Household' 
WHEN a11.RECUR_DISC_DESC LIKE ANY ('%Employee%','%Staff%' )THEN 'Employee'
WHEN a11.RECUR_DISC_DESC LIKE '%VEA%' THEN 'VEA' 
WHEN a11.RECUR_DISC_DESC LIKE '%Renewal%' THEN 'Blackstone'
WHEN a11.RECUR_DISC_DESC LIKE ANY ( '%Student%' , '%Corporate%' , '%Guarantee%' ) THEN 'Other Discounts' 
ELSE 'Agent' END  DISCOUNT_CATEGORY,
	a11.RECUR_DISC_DESC  RECUR_DISC_DESC,
	NVL(a12.DERIVED_MANUFACTURER, 'OTHER')  DERIVED_MANUFACTURER,
	NVL(a18.REPORTED_CHANNEL_GROUP, 'Other')  REPORTED_CHANNEL_GROUP,
	a11.CHANNEL_TYP  CHANNEL_TYP,
	CASE WHEN a14.DES  like '%SIMX%' AND a14.CONTRACT_TYP='SIM Only EVO' AND a14.SOURCE_SYSTEM_CD='60'  Then 'Y'  ELSE 'N' END  SIMX_FLAG,
	a12.MODEL_DESC  MODEL_DESC,
	count(distinct a11.DERIVED_SOURCE_PROMOTION_ID)  TOTAL_ORDERS
from	EDW_USER_VIEWS.P_ORDER_SUMMARY	a11
	left outer join	EDW_USER_VIEWS.P_EQUIPMENT_PRODUCT_DETAIL	a12
	  on 	(a11.DEVICE_PRODUCT_ID = a12.PRODUCT_ID)
	left outer join	BI_MSTR_VIEWS.EVO_ORDER_PRODUCT	a13
	  on 	(a11.DERIVED_SOURCE_PROMOTION_ID = a13.DERIVED_SOURCE_PROMOTION_ID and 
	a11.ORDER_ID = a13.ORDER_ID)
	left outer join	EDW_USER_VIEWS.DIM_PRODUCT	a14
	  on 	(a11.PROMO_SOC_CD = a14.PRODUCT_CD and 
	a11.SUBMIT_DT /* = */ BETWEEN a14.EFFECTIVE_DT AND a14.EXPIRY_DT)
	left outer join	EDW_USER_VIEWS.P_SERVICE_PRODUCT_DETAIL	a15
	  on 	(a11.PROMO_SERVICE_PRODUCT_ID = a15.PRODUCT_ID)
	left outer join	BI_MSTR_VIEWS.ORDER_SUMMARY_RETURN	a16
	  on 	(a11.ORDER_ID = a16.PARENT_ORDER_ID)
	left outer join	EDW_USER_VIEWS.P_ORDER_HEADER	a17
	  on 	(a11.ORDER_ID = a17.ORDER_ID)
	left outer join	EDW_USER_VIEWS.P_CHANNEL_TRACK	a18
	  on 	(a11.CREATION_CHANNEL_ID = a18.CHANNEL_ID and 
	a11.SUBMIT_DT /* = */ BETWEEN a18.EFFECTIVE_DT AND a18.EXPIRY_DT)
	left outer join	EDW_USER_VIEWS.P_CMC_CALENDAR	a19
	  on 	(a11.SUBMIT_DT = a19.CALENDAR_DT and 
	TRUNC(LAST_DAY(a11.SUBMIT_DT)) = a19.LAST_DAY_OF_MONTH)
where	(TRUNC(LAST_DAY(a11.SUBMIT_DT)) between DATE '2024-10-31' and DATE '2025-10-31'
 and not (a11.CHANNEL_TYP in ('Back Office Automation', 'Back Office Disconnection'))
 and NVL(a11.ORDER_SUBTYP, 'Unknown') NOT LIKE '%Reconnection%' 
 and a11.ORDER_STATUS_CD in ('Complete', 'Cancelled', 'Open')
 and not (CASE WHEN a11.MSISDN LIKE '447%' AND a11.PRODUCT_CLASS =  'Fixed Broadband Service' THEN 'HBB-Dongle' WHEN a11.MSISDN LIKE '447%' THEN 'MOB' WHEN a11.PRODUCT_CLASS =  'Fixed Broadband Service' THEN 'HBB'  WHEN a11.PRODUCT_CLASS LIKE 'Accessories' THEN 'ACCESSORIES' ELSE 'UNKNOWN' END in ('UNKNOWN', 'ACCESSORIES', 'HBB-Dongle'))
 and a11.PAYMENT_TYPE_CD in ('Postpaid', 'Prepaid')
 and a17.SEGMENT_DES in ('Consumer', 'Enterprise')
 and a11.ORDER_TYP_DES in ('Flex Upgrade', 'New Connection', 'PretoPost', 'Upgrade')
 and NVL(a18.REPORTED_CHANNEL_GROUP, 'Other') in ('Online', 'Retail Stores', 'Telesales'))
group by	TRUNC(LAST_DAY(a11.SUBMIT_DT)),
	a11.ORDER_TYP_DES,
	a17.SEGMENT_DES,
	a11.ORDER_STATUS_CD,
	a11.PAYMENT_TYPE_CD,
	NVL(a15.ENTERTAINMENT, 'Unknown'),
	NVL(a15.RED_UNLIMITED_GRP, 'Unknown'),
	NVL(a15.RED, 'Unknown'),
	CASE WHEN a11.MSISDN LIKE '447%' AND a11.PRODUCT_CLASS =  'Fixed Broadband Service' THEN 'HBB-Dongle' WHEN a11.MSISDN LIKE '447%' THEN 'MOB' WHEN a11.PRODUCT_CLASS =  'Fixed Broadband Service' THEN 'HBB'  WHEN a11.PRODUCT_CLASS LIKE 'Accessories' THEN 'ACCESSORIES' ELSE 'UNKNOWN' END,
	a17.ORDER_TYP,
	NVL(a15.PRICE_PLAN_GROUP_NM, 'Unknown'),
	a11.SUBMIT_DT,
	a11.ORDER_SUBTYP,
	TRIM(CAST((a19.MTH_DAY_NO+(TD_DAY_OF_WEEK( a19.FIRST_DAY_OF_MONTH -1 ) )-2)/7 AS INTEGER)+1) || '.' || TRIM(a19.CAL_WEEK_DAY_NO) || ' ' || a19.DAY_NM_SHORT,
	NVL(a12.BRAND_DESC || ' ' ||a12.CMRCL_ID_DESC, 'Not classified at this leve'),
	Case when a16.PARENT_ORDER_ID IS NOT NULL THEN 'RETURN' ELSE 'SALE' END,
	a14.DES,
	CASE 
WHEN a14.BEARER_DES IN ('5G', '4G', '3G')  THEN a14.BEARER_DES
ELSE 'UNKNOWN TARIFF' END,
	a14.PRODUCT_DES_2,
	CASE 
WHEN a12.SKU_CD IS NOT NULL AND a12.BEARER LIKE ('%5G%') THEN  '5G DEVICE'
WHEN a12.SKU_CD IS NOT NULL AND a12.BEARER LIKE ('%4G%') THEN  '4G DEVICE'
WHEN a12.SKU_CD IS NOT NULL AND a12.BEARER LIKE ('%3G%') THEN  '3G DEVICE'
WHEN a12.SKU_CD IS NOT NULL AND a12.BEARER NOT LIKE ANY ('%5G%','%4G%','%3G%') THEN  'UNKNOWN DEVICE' END,
	CASE WHEN a11.DEVICE_DESC LIKE ANY ('%APPLE%','%iPAD%') THEN  'APPLE'
WHEN a11.DEVICE_DESC LIKE ANY ('%SAMSUNG%','%GALAXY%') THEN  'SAMSUNG'
WHEN a11.DEVICE_DESC LIKE  '%HUAWEI%' THEN  'HUAWEI'
WHEN a11.DEVICE_DESC LIKE ANY('%PIXEL%','%GOOGLE%') THEN  'GOOGLE'
WHEN a11.DEVICE_DESC LIKE  '%SONY%' THEN  'SONY'
WHEN a11.DEVICE_DESC LIKE  '%NOKIA%' THEN  'NOKIA'
WHEN a11.DEVICE_DESC LIKE ANY ('%MOTOROLA%','%MOTO%') THEN  'MOTOROLA'
WHEN a11.DEVICE_DESC LIKE  '%OPPO%' THEN  'OPPO'
WHEN a11.DEVICE_DESC LIKE  '%XIAOMI%' THEN  'XIAOMI'
WHEN a11.DEVICE_DESC LIKE  '%ALCATEL%' THEN  'ALCATEL'
ELSE 'OTHER' END,
	a11.DEVICE_DESC,
	a11.PROMO_SOC_CD,
	a11.ORDER_TYP_DES,
	a12.SLOT,
	CASE WHEN a11.TRADE_DISC_AMT_INC_VAT > 0 THEN 'TRADE IN OFFER' ELSE 'STANDARD OFFER' END,
	CASE WHEN a11.ORDER_TYP_DES IN ('New Connection') THEN 'ACQUISITION' ELSE 'RETENTION' END,
	NVL(a13.LOAN_AIRTIME_PLAN_FLAG, 'Unknown'),
	NVL((CASE WHEN lower(a13.CONTRACT_TYP) like '%sim only%' THEN a13.PRODUCT_DES_3 ELSE a13.AIRTIME_TIER END), 'Unknown'),
	NVL(a13.REPORTED_PRODUCT, 'Unknown'),
	a14.PRICE_PLAN_BANDING_INC_VAT,
	a11.CONTRACT_TENURE,
	a14.SERVICE_PRODUCT_SET_NM,
	a14.PRODUCT_DES,
	a14.PRODUCT_DES_2,
	a14.DATA_ALLOWANCE_GROUPING,
	CASE WHEN NVL(a15.ENTERTAINMENT, 'Unknown') ='Entertainment'  THEN 'Entertainment' ELSE 'Non Entertainment' END,
	Case When NVL(a15.RED_UNLIMITED_GRP, 'Unknown') IN ('Red','Non Red','Unknown') Then 'Non Unlimited' else a15.RED_UNLIMITED_GRP end,
	a11.TRADEIN_FLAG,
	CASE  
WHEN a11.RECUR_DISC_DESC LIKE '%Trade%' THEN 'Trade-In'
WHEN a11.RECUR_DISC_DESC LIKE '%Promo%' THEN 'Promotional' 
WHEN a11.RECUR_DISC_DESC LIKE '%£%' AND a11.RECUR_DISC_DESC LIKE '%Off%' THEN 'Promotional' 
WHEN a11.RECUR_DISC_DESC LIKE '%£%' AND a11.RECUR_DISC_DESC LIKE '%Plan%' THEN 'Promotional'  
WHEN a11.RECUR_DISC_DESC LIKE '%GBP%' THEN 'Promotional' 
WHEN a11.RECUR_DISC_DESC LIKE '%Vodafone Together%' then 'Vodafone Together'
WHEN a11.RECUR_DISC_DESC LIKE '%House%' THEN 'Household'  
WHEN a11.RECUR_DISC_DESC LIKE '%Additional%' THEN 'Household' 
WHEN a11.RECUR_DISC_DESC LIKE ANY ('%Employee%','%Staff%' )THEN 'Employee'
WHEN a11.RECUR_DISC_DESC LIKE '%VEA%' THEN 'VEA' 
WHEN a11.RECUR_DISC_DESC LIKE '%Renewal%' THEN 'Blackstone'
WHEN a11.RECUR_DISC_DESC LIKE ANY ( '%Student%' , '%Corporate%' , '%Guarantee%' ) THEN 'Other Discounts' 
ELSE 'Agent' END,
	a11.RECUR_DISC_DESC,
	NVL(a12.DERIVED_MANUFACTURER, 'OTHER'),
	NVL(a18.REPORTED_CHANNEL_GROUP, 'Other'),
	a11.CHANNEL_TYP,
	CASE WHEN a14.DES  like '%SIMX%' AND a14.CONTRACT_TYP='SIM Only EVO' AND a14.SOURCE_SYSTEM_CD='60'  Then 'Y'  ELSE 'N' END,
	a12.MODEL_DESC
