select	a11.CHANNEL  CHANNEL,
	a11.LAST_DAY_OF_MONTH  LAST_DAY_OF_MONTH,
	a11.CALENDAR_DT  CALENDAR_DT,
	a11.SEGMENT  SEGMENT,
	((sum(a11.ACQ_HS_TRAFFIC) + sum(a11.RETAILVOLUME)) + sum(a11.ACQUSITION_MOB_TRAFFIC))  ACQHS,
	((sum(a11.ACQ_MBB_TRAFFIC) + sum(a11.RETAILVOLUME)) + sum(a11.ACQUSITION_MOB_TRAFFIC))  ACQMBB,
	((sum(a11.ACQ_SIMO_TRAFFIC) + sum(a11.RETAILVOLUME)) + sum(a11.ACQUSITION_MOB_TRAFFIC))  ACQSIMO,
	((sum(a11.HBB_TRAFFIC) + sum((a11.ACQUSITION_HBB_TRAFFIC + a11.RETENTION_HBB_TRAFFIC))) + sum(a11.RETAILVOLUME))  HBBVOLUME,
	(sum(a11.PAYG_TRAFFIC) + sum(a11.RETAILVOLUME))  PAYGVOLUME,
	(sum(a11.VOXI_TRAFFIC) + sum(a11.RETAILVOLUME))  VOXIVOLUME,
	((sum(a11.TOTAL_ACQUSITION_TRAFFIC) + sum(a11.ACQUSITION_MOB_TRAFFIC)) + sum(a11.RETAILVOLUME))  MOBILEACQUISITION,
	((sum(a11.RET_MOBILE_TRAFFIC) + sum(a11.RETENTION_MOB_TRAFFIC)) + sum(a11.RETAILVOLUME))  MOBILERETENTION
from	BI_MSTR_VIEWS.MSTR_DNC_DEMAND_TRAFFIC	a11
where	(a11.CHANNEL in ('Telesales', 'Retail Stores', 'Online')
 and (a11.LAST_DAY_OF_MONTH >=  DATE '2024-10-31'
 or a11.CURR_MONTH_IND in ('Current Month')))
group by	a11.CHANNEL,
	a11.LAST_DAY_OF_MONTH,
	a11.CALENDAR_DT,
	a11.SEGMENT